version: '3.4'

services:
  gennodeserver:
    image: gennodeserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports: -3030:3030
